---
- name: Reboot machine to finalize setup
  ansible.builtin.reboot:

- name: Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
