---
- name: Install ZSH
  become: true
  ansible.builtin.apt:
    name:
      - zsh
      - zsh-syntax-highlighting
    cache_valid_time: 3600

- name: Clone Oh My Zsh repository
  ansible.builtin.git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "~/.oh-my-zsh"

- name: Clone Syntax Highlighting repository
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Clone Autosuggestions repository
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Clone Completion repository
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-completions"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-completions"

- name: Clone powerlevel10k repository
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k"
    dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"

- name: Upload .zshrc file
  ansible.builtin.copy:
    src: files/.zshrc
    dest: ~/.zshrc

- name: Upload .p10k.zsh file
  ansible.builtin.copy:
    src: files/.p10k.zsh
    dest: ~/.p10k.zsh

- name: Ensure zsh is the default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: "/usr/bin/zsh"
