---
- name: Add Docker repository
  block:
    - name: Download Docker repository keyring
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    cache_valid_time: 3600

- name: Add cron job for Docker disk clean up
  ansible.builtin.cron:
    name: "Docker disk clean up"
    cron_file: "docker-disk-clean-up"
    weekday: "0"
    minute: "0"
    hour: "0"
    job: "docker system prune -af"
    user: root
    state: present
